Traceback (most recent call last):
  File "/home/jakub/coarsegrained-md-neural-ode/sigopt-model.py", line 72, in <module>
    run_and_track_in_sigopt()
  File "/home/jakub/coarsegrained-md-neural-ode/sigopt-model.py", line 61, in run_and_track_in_sigopt
    model, train_loss = trainer.train()
  File "/home/jakub/coarsegrained-md-neural-ode/diffmd/training.py", line 92, in train
    if np.sd(self.loss_meter.losses[-self.stopping_freq:]) > 0.001:
  File "/home/jakub/anaconda3/lib/python3.9/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'sd'
Traceback (most recent call last):
  File "/home/jakub/coarsegrained-md-neural-ode/sigopt-model.py", line 72, in <module>
    run_and_track_in_sigopt()
  File "/home/jakub/coarsegrained-md-neural-ode/sigopt-model.py", line 61, in run_and_track_in_sigopt
    model, train_loss = trainer.train()
  File "/home/jakub/coarsegrained-md-neural-ode/diffmd/training.py", line 92, in train
    if np.sd(self.loss_meter.losses[-self.stopping_freq:]) > 0.001:
  File "/home/jakub/anaconda3/lib/python3.9/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'sd'
Traceback (most recent call last):
  File "/home/jakub/coarsegrained-md-neural-ode/sigopt-model.py", line 72, in <module>
    run_and_track_in_sigopt()
  File "/home/jakub/coarsegrained-md-neural-ode/sigopt-model.py", line 61, in run_and_track_in_sigopt
    model, train_loss = trainer.train()
  File "/home/jakub/coarsegrained-md-neural-ode/diffmd/training.py", line 92, in train
    if np.sd(self.loss_meter.losses[-self.stopping_freq:]) > 0.001:
  File "/home/jakub/anaconda3/lib/python3.9/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'sd'
Traceback (most recent call last):
  File "/home/jakub/coarsegrained-md-neural-ode/sigopt-model.py", line 72, in <module>
    run_and_track_in_sigopt()
  File "/home/jakub/coarsegrained-md-neural-ode/sigopt-model.py", line 61, in run_and_track_in_sigopt
    model, train_loss = trainer.train()
  File "/home/jakub/coarsegrained-md-neural-ode/diffmd/training.py", line 92, in train
    if np.sd(self.loss_meter.losses[-self.stopping_freq:]) > 0.001:
  File "/home/jakub/anaconda3/lib/python3.9/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'sd'
slurmstepd-softnanolab-HP-Z8-G4-Workstation: error: *** JOB 17192 ON softnanolab-HP-Z8-G4-Workstation CANCELLED AT 2022-04-29T14:41:59 ***
